name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Set up dotnet.
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
      - name: Build
        run: dotnet build --configuration Release src/Kubernetes.OperatorSdk -p:VersionPrefix=${{ github.event.release.tag_name }}
      - name: Package
        run: dotnet pack --configuration Release src/Kubernetes.OperatorSdk -p:VersionPrefix=${{ github.event.release.tag_name }} -o dist/
      - name: publish GH
        run: dotnet nuget push dist/*nupkg -k ${{secrets.GITHUB_TOKEN}} -s https://nuget.pkg.github.com/jitesoft/index.json
